id: I5ACC5CBB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:39:26+00:00'
last_modified: '2022-06-08T13:10:56.385197+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC463
  title: 'གངས་ཅན་བོད་ཀྱི་བརྡ་སྤྲོད་རིག་པའི་རྨང་གཞིའི་ཤེས་བྱའི་རེའུ་མིག་མཁས་པའི་འགྲེལ་བ་ཀུན་ལས་བཏུས་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6252':
      image_group_id: I2PD18380
      title: ''
      total_pages: 246
      order: 1
      base_file: 6252.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
