id: P010381
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC463
  title: 'གངས་ཅན་བོད་ཀྱི་བརྡ་སྤྲོད་རིག་པའི་རྨང་གཞིའི་ཤེས་བྱའི་རེའུ་མིག་མཁས་པའི་འགྲེལ་བ་ཀུན་ལས་བཏུས་པ། '
  author: ''
  volumes: {}
